# These keys from from the source of BodegaBot
# https://cheapbotsdonequick.com/source/BodegaBot
# "employees": ["employees","founders","designers","programmers","engineers","product managers","interns"],
#
# NOTES:
# 1. If you're adding somebody other than yourself, make sure you have their permission!
# 2. Please keep each list alphabetized!
#
"employees":
  - abhay
  - bfezga
  - chiangku
  - crabbylions
  - cytochrome
  - dpostsays
  - jeeyoungk
  - jkingdon2000
  - numist
  - onethinline
  - sentiental
  - steckel
  - tuanycakes
  - vslavich
"founders":
"designers":
  - onethinline
  - vslavich
"programmers":
  - abhay
  - chiangku
  - cytochrome
  - dpostsays
  - jeeyoungk
  - jkingdon2000
  - numist
  - sentiental
  - steckel
"engineers":
  - abhay
  - chiangku
  - cytochrome
  - dpostsays
  - jeeyoungk
  - jkingdon2000
  - numist
  - sentiental
  - steckel
  - tuanycakes
"product managers":
  - bfezga
  - crabbylions
  - vslavich
"interns":
